import Head from 'next/head';
import { lazy } from 'react';
import { API_URL_NOW_PLAYING } from '../contants/movieContants';
import useMovies from '../hooks/useMovies';
import MoviesContext from '../contexts/MoviesContext';
import { useRouter } from 'next/router';

const SearchMovies = lazy(() => import('../components/movies/SearchMovies'));
const ListMovies = lazy(() => import('../components/movies/ListMovies'));
const DetailMovies = lazy(() => import('../components/movies/DetailMovies'));

export default function Home() {
  const {query} = useRouter();
  const movies = useMovies(`${API_URL_NOW_PLAYING}1`);

  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoviesContext.Provider value={{...movies}}>
        {query?.id ?
        <DetailMovies/> :
        <>
          <SearchMovies/>
          <main style={{position: 'relative', top: '100px'}}>
            <ListMovies/>
          </main>
        </>}
      </MoviesContext.Provider>
    </>
  )
}
